colors = {
    f"raw_images": "black",
    f"untrained_alexnet": "gray",
    f"alexnet_normal": "#1f77b4",
    f"alexnet_multi-steps": "mediumvioletred",
    f"alexnet_all_s04": "darkgreen",
    f"alexnet_mix_s01": "lime",
    f"alexnet_mix_s04": "darkorange",
    f"alexnet_mix_p-blur_s01": "lime",
    f"alexnet_mix_p-blur_s04": "darkorange",
    f"alexnet_mix_s10": "hotpink",
    f"alexnet_mix_p-blur_s01_no-blur-1label": "limegreen",
    f"alexnet_mix_p-blur_s01_no-blur-8label": "lighteseagreen",
    f"alexnet_mix_p-blur_s04_no-blur-1label": "orangered",
    f"alexnet_mix_p-blur_s04_no-blur-8label": "gold",
    f"alexnet_random-mix_s00-05": "green",
    f"alexnet_random-mix_s00-10": "darkgreen",
    f"alexnet_trained_on_SIN": "brown",
    f"vone_alexnet": "navy",
}

lines = {
    f"raw_images": "--",
    f"untrained_alexnet": ":",
    f"alexnet_normal": ":",
    f"alexnet_multi-steps": "-",
    f"alexnet_all_s04": "-",
    f"alexnet_mix_s01": "-",
    f"alexnet_mix_s04": "-",
    f"alexnet_mix_p-blur_s01": "-",
    f"alexnet_mix_p-blur_s04": "-",
    f"alexnet_mix_s10": "-",
    f"alexnet_mix_p-blur_s01_no-blur-1label": "-",
    f"alexnet_mix_p-blur_s01_no-blur-8label": "-",
    f"alexnet_mix_p-blur_s04_no-blur-1label": "-",
    f"alexnet_mix_p-blur_s04_no-blur-8label": "-",
    f"alexnet_random-mix_s00-05": "-",
    f"alexnet_random-mix_s00-10": "-",
    f"alexnet_trained_on_SIN": "-",
    f"vone_alexnet": "-",
}
